---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: productappdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: productapp
 template:
  metadata:
   name: productapppod
   labels:
     app: productapp
  spec: 
    containers:
    - name: productappcontainer
      image: animireddy/productapp
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: productappsvc
spec:
  type: LoadBalancer
  selector:
   app: productapp
  ports:
   - port: 80
     targetPort: 8080
...
